services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    env_file: "./backend/.env"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_GRAPHQL_ENDPOINT=http://backend:3000/graphql
    depends_on:
      - backend
    restart: unless-stopped
